### ISSUE TITLE
Xcode 9 beta: libogg does not compile

### ISSUE THREAD

**Issue by jacobjennings** [brion/OGVKit-Specs#3]
![screen shot 2017-06-14 at 1 51 07 pm](https://user-images.githubusercontent.com/1038927/27154072-95e0595c-5108-11e7-8dba-9cdb64ff3d8a.png)

**Comment by jacobjennings** [comment]
#  include <sys/types.h>
fixed it, but it looks like sources are not hosted on github?

**Comment by natangr** [comment]
Same problem here.

**Comment by bvibber** [comment]
This should be fixed by the latest spec update from this weekend -- @natangr re-run `pod repo update` and `pod install` to make sure you've got the up to date version.

(Original sources for libogg use `#include <inttypes.h>`, which I patched out to get it to build as a proper "module" in CocoaPods. Under the iOS 10 SDK it worked to just remove the `#include`, but in iOS 11 SDK we have to explicitly `#include <sys/types.h>` instead.)
